
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tania
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Course Distribution System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CSE", "BBA", "LLB" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Semester");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Department");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setLabel("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                to= jComboBox1.getSelectedItem().toString();
                from = jComboBox2.getSelectedItem().toString();
                if ( from.equals("CSE") ){
                    switch(to){
                        case "1" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nCSE-111  Fundamentals of Computers 3.0\nCSE-123  Discrete Mathematics 1.5\nMAT-101   Calculus 3.0\nENG-101  English Language 3.0");   
                        break ;
                        case "2" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 13.5\nCSE-113 Structured Programming Language 3.0\nCSE-114 Structured Programming Language Lab 1.5\nMAT-103 Matrices, Vector Analysis and Geometry 3.0\nGED-101 Bangladesh Studies 3.0\nPHY-101 Mechanics, Wave, Heat and Thermodynamics 3.0");
                        break ;
                        case "3" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nCSE-121 Basic Electrical Engineering 3.0\nCSE-122 Basic Electrical Engineering Lab 1.5\nPHY-101 Mechanics, Wave, Heat and Thermodynamics 3.0\nCSE-131 Data Structure 3.0\nCSE-132 Data Structure Lab 1.5");    
                        break ;
                        case "4" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nCSE-211 Object Oriented Programming Language 3.0\nCSE-212 Object Oriented Programming Language Lab 1.5\nCSE-213 Electronic Devices and Circuits 3.0\nCSE-214 Electronic Devices and Circuits Lab 1.5\nSTA-201 Basic Statistics and Probability 3.0");    
                        break ;   
                        case "5" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 15\nCSE-211 Object Oriented Programming Language 3.0\nCSE-212 Object Oriented Programming Language Lab 1.5\nCSE-221 Digital Logic Design 3.0\nCSE-222 Digital Logic Design Lab 1.5\nBBA-201 Cost and Management Accounting 3.0\nCSE-317 Simulation and Modeling 3.0");    
                        break ;
                        case "6" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nMAT-201 Numerical Methods 3.0\nBBA-201 Cost and Management Accounting 3.0\nCSE-311 Computer Architecture 3.0\nCSE-317 Simulation and Modeling 3.0\n");
                        break ;
                        case "7" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 14\nCHE-101 Fundamentals of Chemistry 3.0\nCSE-216 Engineering Drawings 3.0\nECO-201 Principles of Economics 3.0\nCSE-311 Computer Architecture 3.0\nCSE-317 Simulation and Modeling 3.0");    
                        break ;
                        case "8" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nCSE 317 Simulation and Modeling 3.0\nCSE-321 Microprocessor and Interfacing 3.0\nCSE-322 Microprocessor and Interfacing Lab 1.5\nCSE-331 Operating System and System Programming 3.0\nCSE-332 Operating System and System Programming Lab 1.5");
                        break ;
                        case "9" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 9\nCSE-321 Microprocessor and Interfacing 3.0\nCSE-322 Microprocessor and Interfacing Lab 1.5\nCSE-331 Operating System and System Programming 3.0\nCSE-332 Operating System and System Programming Lab 1.5");
                        break;
                        case "10" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 13.5\nCSE-331 Operating System and System Programming 3.0\nCSE-332 Operating System and System Programming Lab 1.5\nCSE-411 Artificial Intelligence 3.0\nCSE-412 Artificial Intelligence Lab 1.5\nCSE-421 Compiler Construction 3.0\nCSE-422 Compiler Construction Lab 1.5");  
                        break;
                        case "11" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 11\nCSE-331 Operating System and System Programming 3.0\nCSE-332 Operating System and System Programming Lab 1.5\nCSE-413 Web Engineering 3.0\nCSE-414 Web Engineering Lab 1.5\nCSE-400 Thesis/Project I 2.0");  
                        break;
                        case "12" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 8\nCSE-413 Web Engineering 3.0\nCSE-414 Web Engineering Lab 1.5\nCSE-402 Thesis/Project II 2.0\nCSE-404 Viva Voce 1.5");  
                        break;    
                    }
                }
                if ( from.equals("LLB") ){
                    switch(to){
                        case "1" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nLAW–101 Jurisprudence-1 3\nLAW–103 Muslim Law-1 3\nENG–101 English Language-1 3\nCSE–100 Computer Skill 3");  
                        break;
                        case "2" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 11\nLAW–105 Jurisprudence-II 3\nLAW–107 Law of Contract-1 3\nLAW–109 Muslim Law-II 2\nENG–103  English Language-II 3");  
                        break;
                        case "3" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 11\nLAW–111 Law of Contract-II 2\nLAW–113 Law of Tort 3\nLAW–115 Hindu & Roman Law 3\nGED–101 Bangladesh Studies 3");  
                        break;
                        case "4" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nLAW–201  Constitutional Law of Bangladesh-1 3\nLAW–203 Constitutional Law of UK & USA 3\nLAW–205 Government & Politics 3\nLAW-207 Legal History and Legal system of Bangladesh 3");  
                        break;  
                        case "5" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nLAW–209 Transfer of Property Act 3\nLAW–211 Constitutional Law of Bangladesh-II and General Clauses Act 3\nLAW–213 Labour and Industrial Law–1 3\nLAW–215  Land Laws of Bangladesh-1 3");  
                        break;
                        case "6" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 11\nLAW–217 Labour and Industrial Law–II 2\nLAW-219 Company Law and Partnership Act 3\nLAW–221 Land Laws of Bangladesh–II 3\nLAW–223 Registration & Public Demands Recovery Act 3");  
                        break;
                        case "7" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nLAW–301  Penal Code–1  3\nLAW–303 Criminal Procedure Code-1 3\nLAW–305 Law of Taxation 3\nLAW–307 Stamp & Suit valuation Act 3");  
                        break;
                        case "8" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nLAW–309 Penal Code–II  3\nLAW–311 Criminal Procedure Code–II 3\nLAW – 313 Law relating to protection of Women and Children & Special Powers Act 3\nLAW–315 Equity,Trust and Specific Relief Act 3");  
                        break;  
                        case "9" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nLAW–317 Mercantile Law 3\nLAW–319 Public International Law–I 3\nLAW–321  Criminology 3\nLAW–323 Administrative Law 3");  
                        break;
                        case "10" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nLAW–401 Law of Evidence–1 3\nLAW–403 Civil Court & Court fees Act 3\nLAW–405  Civil Procedure Code–I 3\nLAW–407 Public International Law–II 3");  
                        break;
                        case "11" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nLAW–409 Law of Evidence–II 2\nLAW–411 Civil Procedure Code–II & Limitation Act 3\nLAW-413 Laws of War, Air and Outer Space  3\nLAW–415 Comparative Law   3");  
                        break;
                        case "12" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nLAW–417  Civil & Criminal Drafting  3\nLAW–419  Environmental Law 3\nLAW–421 Project and Moot Court & Bar Council Order 3\nLAW–400 Viva Voce 3");  
                        break;  
                    }
                }
                 if ( from.equals("BBA") ){
                    switch(to){
                        case "1" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 09\nENG- 011 Remedial English 0\nBUS-111 Introduction to Business Comprehensive 3\nCSE-113 Introduction to Computer Applications 3\nMGT-115 Fundamentals  of Management 3");  
                        break;
                        case "2" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nACC-121Principles of Accounting 3\nUGE-123 Bangladesh Studies 3\nFIN-125 Principles of Business Finance 3\nENG-127  Functional English-1 3");  
                        break;
                        case "3" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nENG-131  Functional English-2 03\nMKT-133 Principles of Marketing 3\nUGE-135Industrial Sociology and Psychology 3\nMAT-137 Basic Mathematics 3");  
                        break;
                        case "4" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nMAT-211 Mathematics for Business Decisions (Prerequisite MAT-137) 3\nBUS-213 Business Communication 3\nACC-215 Intermediate Accounting (Pre-requisite ACC- 121) 3\nECO-217 Microeconomics 3");  
                        break;  
                        case "5" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nECO-221 Macroeconomics (Pre-requisite ECO-217) 3\nUGE-223  Ecology and Environment 3\nACC-225  Cost Accounting 3\nSTA-227 Business Statistics-1 3");  
                        break;
                        case "6" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nSTA-231 Business Statistics-2 (Prerequisite STA- 227) 3\nFIN-233 Banking and Insurance 3\nACC-235 Management Accounting 3\nMKT-237 Marketing Management (Pre-requisite MKT-133) 3");  
                        break;
                        case "7" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nMGT-311  Organizational Behavior 3\nMGT-313   Management Information Systems  (Prerequisite MGT- 115) 3\nBUS-315 Taxation in Bangladesh 3\nBUS-317 Business law 3");  
                        break;
                        case "8" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nHRM-321 Human Resource Management 3\nBUS-323 Entrepreneurship Development 3\nMGT-325 Production and Operations Management 3\nBUS-327 Strategic Management 3");  
                        break;  
                        case "9" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 12\nFIN-331 Financial Management 3\nBUS-333  Business Ethics and CSR 3\nBUS-335 International Business 3\nBUS-337 Business Research Methods 3");  
                        break;
                        case "10" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 9\nACC-411 Advanced Financial Accounting 3\nACC-413 Advanced Cost Accounting 3\nACC-415 Accounting Information Systems 3");  
                        break;
                        case "11" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 9\nACC-421 Accounting Theory 3\nACC-423 Advanced Management Accounting 3\nACC-425 Accounting for Government and Not-for-profit Organizations 3");  
                        break;
                        case "12" :
                        JOptionPane.showMessageDialog(null, "Total Credit: 4\nBUS-499 Internship 4");  
                        break;  
                    }
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
String   to ;
String  from;
}

